### PR TITLE
Support Safari on Apple devices.

### LINKED ISSUE #626: feat: support Safari(iPad OS)
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

feat: support Safari(iPad OS)

### 描述 Motivation

被 https://twitter.com/laike9m/status/1648254568269221888?s=20 打动

### Solution

Safari Extension 似乎是支持 Mobile 的！

https://alvarotrigo.com/blog/chrome-extensions-ipad/

### 还有其他内容吗？Anything else?

n/a

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

### LINKED ISSUE #747: 可否开发Safari插件？
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望开发Safari插件

### 描述 Motivation

平时很少使用Chrome，反而Mac的Safari是主力浏览器，翻译很好用，希望能有Safari的版本

### Solution

_No response_

### 还有其他内容吗？Anything else?

_No response_

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

### LINKED ISSUE #779: 有没有考虑过开发移动端
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望在移动端上也能使用

### 描述 Motivation

平时使用电脑不在身边时，也会有翻译的需求，所以希望能开发移动端供手机版使用，感谢！

### Solution

_No response_

### 还有其他内容吗？Anything else?

_No response_

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by yeatse**
## What I did for now:
- [x] Create a safari extension project from chromium one using [safari-web-extension-converter](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari)
- [x] Added some touch event handlers to support mobile devices

## What to be done in the future:
- [ ] Add a new job in workflow script to continuously build this safari project
- [ ] Update the UI so that it performs better on small screen devices
- [ ] Publish this plugin to AppStore (Maybe the we should change the product name to meet the copyright?)

## Screenshots:
- macOS

https://github.com/openai-translator/openai-translator/assets/6036532/c40f559c-1be8-4a81-a6c7-b41ed396b5b4

- iPadOS

https://github.com/openai-translator/openai-translator/assets/6036532/48208f3e-4a0c-46b0-a852-97fb48b81a6a

- iOS

https://github.com/openai-translator/openai-translator/assets/6036532/aa63508a-d2fb-4dfe-be59-9390c3cc9291

Closes #626
Closes #747 
Closes #779

### CODE REVIEW

**Comment by yetone** [comment]
Great job! I'll test it on my iPhone next, is there a build step?

**Comment by yeatse** [comment]
> Great job! I'll test it on my iPhone next, is there a build step?

1. run `make build-browser-extension`
2. open `src-safari/OpenAI Translator.xcodeproj` from Xcode and build it.

You need Ventura 13.4, Xcode 14.3 and iOS 16.4 or above to make it function properly since this extension relies on some features that [only latest Safari can offer](https://webkit.org/blog/13966/webkit-features-in-safari-16-4/#safari-web-extensions).

**Comment by yeatse** [comment]
@yetone hi, what can I help to make this pr get merged? I'm going to submit another pull request that depends on this one.

**Comment by yetone** [comment]
@yeatse My deepest apologies! I've been extremely busy these past few days and didn't have the time to merge this PR, but it's now done. I hope this hasn't caused you too much inconvenience.

**Comment by noahyao1024** [comment]
Hi, Bro May I ask how to process this error? "openai-translator/dist/browser-extension/chromium/userscript.js-E /Users/morysky/Downloads/openai-translator/dist/browser-extension/chromium/userscript.js-E: No such file or directory".

I just initialized the node environment, and encounter this error when building on Xcode.

**Comment by yeatse** [comment]
> Hi, Bro may I ask how to process this error? "openai-translator/dist/browser-extension/chromium/userscript.js-E: No such file or directory".
> 
> I just initialized the node environment, and encounter this error when building on Xcode, perhaps some crucial steps are missed?

You should run `make build-browser-extension` first to generate necessary files required by the safari target. If Xcode complaints some file is missing, just delete it from the Xcode project navigator.

**Comment by noahyao1024** [comment]
> 

Thanks, deleting has worked!!!

**Comment by shwangdev** [comment]
how to install it in IpadOS?

**Pull request merged**
