### PR TITLE
chatgpt web模式修复

### PR DESCRIPTION
**Pull request by ahern88**
由于chatgpt的api调整，导致web模式无法进行翻译，通过修改为http请求+websocket做数据调用。

### CODE REVIEW

**Comment by yetone** [comment]
image

奇怪，我这里好像是好的

**Comment by akira0245** [comment]
我用着也没问题

**Comment by ahern88** [comment]
> image
> 奇怪，我这里好像是好的

image

**Comment by ahern88** [comment]
就是针对这个问题的修复, [[Bug] Not working while using ChatGPT(Web) #1288](https://github.com/openai-translator/openai-translator/issues/1288)

**Comment by akira0245** [comment]
动画

**Comment by ahern88** [comment]
> 动画 [ 动画 ](https://private-user-images.githubusercontent.com/33274390/305776169-f57dac0f-1336-4564-8f58-eca5199199cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE4NzMsIm5iZiI6MTcwODMxMTU3MywicGF0aCI6Ii8zMzI3NDM5MC8zMDU3NzYxNjktZjU3ZGFjMGYtMTMzNi00NTY0LThmNTgtZWNhNTE5OTE5OWNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDc5MjE1YWY1ZTg1NzRhNzgyMTVkNzc5MDc3MmMzMjdhNDM4NmM1YTEzOWMyNzE5NWU5OTMxZWRkYTdmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA5hIlPAfFl2a0kgvtT6Vkc2rX2PrfBDNRGJxxWf8rQ) [ ](https://private-user-images.githubusercontent.com/33274390/305776169-f57dac0f-1336-4564-8f58-eca5199199cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE4NzMsIm5iZiI6MTcwODMxMTU3MywicGF0aCI6Ii8zMzI3NDM5MC8zMDU3NzYxNjktZjU3ZGFjMGYtMTMzNi00NTY0LThmNTgtZWNhNTE5OTE5OWNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDc5MjE1YWY1ZTg1NzRhNzgyMTVkNzc5MDc3MmMzMjdhNDM4NmM1YTEzOWMyNzE5NWU5OTMxZWRkYTdmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA5hIlPAfFl2a0kgvtT6Vkc2rX2PrfBDNRGJxxWf8rQ)

这就不太科学了，我试了好多次是不行的。然后看了下代码，发现老的方式是使用Server-sent Events方式与chatgpt交互，而新的网页版采用了websocket，所以我将实现改成了websocket

**Comment by EastKing** [comment]
我这里还是有这个问题！希望能突击解决一下，谢谢了。

**Comment by yetone** [comment]
> > 动画
> >       
> >         [
> >           
> >             动画
> >           
> >         ](https://private-user-images.githubusercontent.com/33274390/305776169-f57dac0f-1336-4564-8f58-eca5199199cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE4NzMsIm5iZiI6MTcwODMxMTU3MywicGF0aCI6Ii8zMzI3NDM5MC8zMDU3NzYxNjktZjU3ZGFjMGYtMTMzNi00NTY0LThmNTgtZWNhNTE5OTE5OWNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDc5MjE1YWY1ZTg1NzRhNzgyMTVkNzc5MDc3MmMzMjdhNDM4NmM1YTEzOWMyNzE5NWU5OTMxZWRkYTdmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA5hIlPAfFl2a0kgvtT6Vkc2rX2PrfBDNRGJxxWf8rQ)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/33274390/305776169-f57dac0f-1336-4564-8f58-eca5199199cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE4NzMsIm5iZiI6MTcwODMxMTU3MywicGF0aCI6Ii8zMzI3NDM5MC8zMDU3NzYxNjktZjU3ZGFjMGYtMTMzNi00NTY0LThmNTgtZWNhNTE5OTE5OWNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDc5MjE1YWY1ZTg1NzRhNzgyMTVkNzc5MDc3MmMzMjdhNDM4NmM1YTEzOWMyNzE5NWU5OTMxZWRkYTdmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA5hIlPAfFl2a0kgvtT6Vkc2rX2PrfBDNRGJxxWf8rQ)
> >         
> >        [ 动画 ](https://private-user-images.githubusercontent.com/33274390/305776169-f57dac0f-1336-4564-8f58-eca5199199cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE4NzMsIm5iZiI6MTcwODMxMTU3MywicGF0aCI6Ii8zMzI3NDM5MC8zMDU3NzYxNjktZjU3ZGFjMGYtMTMzNi00NTY0LThmNTgtZWNhNTE5OTE5OWNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDc5MjE1YWY1ZTg1NzRhNzgyMTVkNzc5MDc3MmMzMjdhNDM4NmM1YTEzOWMyNzE5NWU5OTMxZWRkYTdmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA5hIlPAfFl2a0kgvtT6Vkc2rX2PrfBDNRGJxxWf8rQ)
> >       
> >         [
> >           
> >             动画
> >           
> >         ](https://private-user-images.githubusercontent.com/33274390/305776169-f57dac0f-1336-4564-8f58-eca5199199cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE4NzMsIm5iZiI6MTcwODMxMTU3MywicGF0aCI6Ii8zMzI3NDM5MC8zMDU3NzYxNjktZjU3ZGFjMGYtMTMzNi00NTY0LThmNTgtZWNhNTE5OTE5OWNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDc5MjE1YWY1ZTg1NzRhNzgyMTVkNzc5MDc3MmMzMjdhNDM4NmM1YTEzOWMyNzE5NWU5OTMxZWRkYTdmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA5hIlPAfFl2a0kgvtT6Vkc2rX2PrfBDNRGJxxWf8rQ)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/33274390/305776169-f57dac0f-1336-4564-8f58-eca5199199cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE4NzMsIm5iZiI6MTcwODMxMTU3MywicGF0aCI6Ii8zMzI3NDM5MC8zMDU3NzYxNjktZjU3ZGFjMGYtMTMzNi00NTY0LThmNTgtZWNhNTE5OTE5OWNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDc5MjE1YWY1ZTg1NzRhNzgyMTVkNzc5MDc3MmMzMjdhNDM4NmM1YTEzOWMyNzE5NWU5OTMxZWRkYTdmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA5hIlPAfFl2a0kgvtT6Vkc2rX2PrfBDNRGJxxWf8rQ)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/33274390/305776169-f57dac0f-1336-4564-8f58-eca5199199cb.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMTE4NzMsIm5iZiI6MTcwODMxMTU3MywicGF0aCI6Ii8zMzI3NDM5MC8zMDU3NzYxNjktZjU3ZGFjMGYtMTMzNi00NTY0LThmNTgtZWNhNTE5OTE5OWNiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDAyNTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDc5MjE1YWY1ZTg1NzRhNzgyMTVkNzc5MDc3MmMzMjdhNDM4NmM1YTEzOWMyNzE5NWU5OTMxZWRkYTdmODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA5hIlPAfFl2a0kgvtT6Vkc2rX2PrfBDNRGJxxWf8rQ)
> 
> 这就不太科学了，我试了好多次是不行的。然后看了下代码，发现老的方式是使用Server-sent Events方式与chatgpt交互，而新的网页版采用了websocket，所以我将实现改成了websocket

我记得 ChatGPT 已经改回 SSE 了

**Comment by tinboxw** [comment]
我这里也出现这个问题了，无法使用chatgpt-web

**Comment by lwd-temp** [comment]
当这个问题发生时，`https://chat.openai.com/backend-api/conversation`的返回内容是

```json
{
  "wss_url": "wss://chatgpt-async-webps-prod-eastus-22.webpubsub.azure.com/client/hubs/conversations?access_token=（移除token）",
  "expires_at": "2024-（移除时间戳）",
  "conversation_id": "（移除id）",
  "response_id": "（移除id）-（移除机场代号）",
  "websocket_request_id": null
}
```

**Comment by yetone** [comment]
抱歉，由于 ChatGPT 已回滚回 SSE，所以关闭此 PR

**Pull request closed without merging**
