### PR TITLE
fix: code highlight

### LINKED ISSUE #778: 🔥🔥🔥 [Bug] 启用插件导致页面里包含的代码块渲染不正常
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.53

### 系统/浏览器版本 System/Browser version

Chrome 113.0.0.0

### 复现步骤 Reproduce step

+ 从Github Release 安装最新的浏览器插件
+ 打开一个包含代码块的网址，如 [StackOverflow](https://stackoverflow.com/questions/42479902/what-does-view-do-in-pytorch)

### 你看到了什么错误？What errors do you see?

禁用插件前所有代码块都被渲染成 [object Object]，禁用插件后渲染正常，如下图

### 你期望看到什么？What did you expect to see?

插件不影响页面渲染

### 还有其他的内容吗？Anything else?

题外话：个人在该项目基础上实现了一些小功能，主要包含以下三点：
+  **第三方 ChatGPT 接口的支持**，目前支持诸如 [chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)、[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)、[chatbot-ui](https://github.com/mckaywrigley/chatbot-ui)、[chatgpt-vercel](https://github.com/ourongxing/chatgpt-vercel) 以及 [AILink](https://github.com/vastsa/AILink) 等

+ **不同 provider 之间自由切换，配置之间不会相互覆盖**

+ 另外就是可以像现在的机场一样 **支持订阅 APIKey 及 接口**

不知作者是否感兴趣，如果感兴趣的话，我可以提交PR。
> 如果感兴趣，可以去我的 [项目地址](https://github.com/wzdnzd/openai-translator/tree/customize) 下载份源码编译试玩一下。由于适配的比较杂，加之最近刚开始学写前端，可能代码看上去个性化方面会比较强😅

> 另外还有个小建议，作者可以考虑一下：感觉 translate 这部分代码可以抽象成接口。组装请求的 `body` 及 `headers` 以及如何解析/处理数据交给不同的 provider（对应的实现类），主流程通过 `模板方法模式` 实现调用，甚至可以预留一些 `预处理` 及 `后处理` 扩展点。这样方便添加新的 provider 及 代码维护。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

### PR DESCRIPTION
**Pull request by fengkx**
Fixes #778 

This is caused by react-syntax-highlighter using refractor v3 https://github.com/wooorm/refractor/issues/59 Prism is a singletone, So It affect all site use Prism

The original repo of react-syntax-highlighter has not been updated for a long time so I publish my own package to fix the problem. https://github.com/react-syntax-highlighter/react-syntax-highlighter/pull/521

### CODE REVIEW

**Comment by frostming** [comment]
IMO the problem is why it affects the code outside of OpenAI translator when **mounted**.

**Comment by yetone** [comment]
LGTM! That's crazy!

**Comment by yetone** [comment]
临时把 OpenAI Translator 从 Chrome Store 下线了，防止用户更新到最新的有问题的版本

**Comment by yetone** [comment]
https://github.com/react-syntax-highlighter/react-syntax-highlighter/issues/513

**Pull request merged**
