### PR TITLE
fix Web API

### PR DESCRIPTION
**Pull request by BlackStar1453**
GPT-3.5 also needs an arkose token now. I put the arkose script in , now  we can use GPT-4 and GPT-3.5 in the Web API.

### CODE REVIEW

**Comment by yetone** [comment]
‌‌‌‌‌‌‌So great.

**Comment by 0x0918** [comment]
为啥这个fixed没有合并成功啊，期待合并

**Comment by RtYkk** [comment]
I hope you're doing well. I noticed that this pull request has been pending for a while, and I appreciate the changes you've made. However, I'm curious about the delay in merging. Is there a particular reason for the delay, or are there additional changes or information needed before it can be merged?

It's an essential fix for the severe bug that has been affecting the community, and I believe its integration would greatly benefit Program A. Knowing the timeline for merging this would be incredibly helpful. Thank you for your continued work on the project.

**Comment by RtYkk** [comment]
Hi yezone,

I noticed that this pull request has been pending for a while, and I appreciate the changes you've made. However, I'm curious about the delay in merging. Is there a particular reason for the delay, or are there additional changes or information needed before it can be merged?

It's an essential fix for the severe bug that has been affecting the community, and I believe its integration would greatly benefit OpenAI Translator. This time of waiting for the merge and not being able to use OpenAI Translator is really painful for me. Knowing the timeline for merging this would be incredibly helpful. Thank you for your continued work on the project.

**Comment by yetone** [comment]
‌‌@RtYkk Sorry, the reason why this PR has not been merged is because all the CI for this PR have reported errors, so it cannot be merged forcefully. However, my main job is very busy and I don't have time to deal with the issue of CI errors in this PR.

**Comment by RtYkk** [comment]
@yetone Thanks for your clarification. I fully understand the issue with the CI errors. There's no doubt that your main job is much more important. I will wait patiently. Have a good day.

**Comment by yetone** [comment]
‌‌‌@BlackStar1453 Hello, thank you for your PR. Have you tested this PR locally? It doesn't work on my end.

image

**Comment by BlackStar1453** [comment]
@yetone yes it works well on my end. Maybe I missed something, I will try to figure out what exactly happened.

**Comment by BlackStar1453** [comment]
@yetone sorry, it was my oversight. I forgot to add the script file in the public folder. But it seems  there might still be some issues here. I can't open and use it in this branch, but it works fine in my own branch. It appears there might be some conflicting settings, and I'm not sure what happened.

**Comment by BlackStar1453** [comment]
> ‌‌‌@BlackStar1453 Hello, thank you for your PR. Have you tested this PR locally? It doesn't work on my end.
> 
> image

This error won't affect the retrieval of the Arkose token. Can you try to simply ignore it?

**Comment by yetone** [comment]
‌‌‌‌‌‌‌@BlackStar1453 If you have already placed `api.js` in the `public` directory, can you delete `api.js` from the `src` directory?

**Comment by BlackStar1453** [comment]
@yetone actually I can't. If you delete 'api.js,' you won't be able to use the ChatGPT Web API by selecting text with your mouse on the webpage. This is likely because loading external scripts to generate Arkose tokens on the webpage isn't possible. If you delete it, you'll only be able to use ChatGPT Web by opening the extension from the upper-right corner.

**Comment by yetone** [comment]
‌‌‌@BlackStar1453 I am confused by the presence of `api.js` in both the `src` directory and the `public` directory.

**Comment by RtYkk** [comment]
It seems that ChatGPT Web is working fine now even without this fix? That's really weird. What changed?

**Comment by BlackStar1453** [comment]
@yetone @RtYkk Actually it wasn't fixed. This is because GPT-3.5 no longer needs to use the Arkose token. Additionally, there is a bug in the latest version. When you select GPT-4, you are actually using GPT-3.5.

**Comment by ZFLIU09** [comment]
I got it for a long time but have not been able to change this situation. Sorry, I just registered on GitHub and started learning programming. In chatgptweb service, it shows that "ChatGPT Web error: Our systems have detected unusual activity from your system. Please try again later."

**Comment by djmisterjon** [comment]
i also get this message for few hours ""ChatGPT Web error: Our systems have detected unusual activity from your system. Please try again later."
But it seem solved by iteself !

**Pull request closed without merging**
