### PR TITLE
Firefox plugin support

### PR DESCRIPTION
**Pull request by kb5000**
This fix primarily includes updates to package Firefox as an add-on and upload it to the Firefox Browser Add-ons store:

1. Changed the icon to a square format to pass automated tests.
2. Reduced the size of each file in the add-on by dynamically importing tiktoken, ensuring compliance with add-on automated tests.

Packaging and uploading to the Firefox Browser Add-ons store should now proceed without issues.

### CODE REVIEW

**Comment by yetone** [comment]
‌‌You did great things! Thank you very much!

**Comment by cmj2002** [comment]
Still can't find this in Firefox Add-ons store, and the badge in README says it is invalid. Is it waiting for approval of Firefox Add-ons store or is something else happening?

**Comment by kb5000** [comment]
> Still can't find this in Firefox Add-ons store, and the badge in README says it is invalid. Is it waiting for approval of Firefox Add-ons store or is something else happening?

I've just tested the automated packaging and uploading process for the Firefox Add-ons store, and it should work fine. However, it seems that the author needs to resubmit this extension in order to restore it to a usable state.

**Comment by cmj2002** [comment]
I even can't build and install the extension myself due to the [signing policy of firefox](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox)

> I've just tested the automated packaging and uploading process for the Firefox Add-ons store, and it should work fine. However, it seems that the author needs to resubmit this extension in order to restore it to a usable state.

@yetone Can you resubmit it to Firefox Add-ons store?

**Comment by kb5000** [comment]
> I even can't build and install the extension myself due to the [signing policy of firefox](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox)

If you're keen to use the extension quickly, you might want to try manually installing [this](https://github.com/kb5000/openai-translator-firefox/releases/tag/v0.0.89) forked testing version until the author submits the official one. Hope this helps!

**Comment by changcui** [comment]
excellent work!

**Pull request merged**
